#!/bin/bash

#Recupera pelo xrandr os monitores HDMI conectados
DISPLAY_LIST=$(xrandr | grep -w connected | awk '{ ORS=";" } { print $1 }')

#Faz um split na lista de hdmi encontrados, transformando em um array
IFS=';' read -ra DISPLAY_ARRAY <<< "$DISPLAY_LIST"

#Itera em toda a lista desligando os monitores HDMI que nao estao conectados
#E guarda o o nome do monitor HDMI conectado (Se houver)
for idx in "${!DISPLAY_ARRAY[@]}"; do
	HDMI="${DISPLAY_ARRAY[idx]}"
	xrandr --output $HDMI --auto
done

